apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: {{ default "kubeups" .Values.namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: {{ default "prom/prometheus:latest" .Values.prometheus.image.name | quote }}
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        
        - name: prometheus-storage-volume
        {{ if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "kubeups.fullname" . }}
        {{ else }}
          emptyDir: {}
        {{end}}


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: {{ default "kubeups" .Values.namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
        - name: grafana
          image: {{ default "grafana/grafana:latest" .Values.grafana.image.name | quote }}
          env:
          - name: GF_AUTH_BASIC_ENABLED
            value: {{ default "true" .Values.grafana.auth.basic.enabled | quote }}
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: {{ default "true" .Values.grafana.auth.anonymous.enabled | quote }}
          ports:
            - containerPort: 3000
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage
          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false
          - name: grafana-config
            mountPath: /etc/grafana/provisioning/dashboards/dashboardConfig.yaml
            subPath: dashboardConfig.yaml
          - mountPath: /var/lib/grafana/dashboards/kubeUPS-dashboard.json
            name: dashboard-templates
            subPath: kubeUPS-dashboard.json
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-config
          configMap:
            name: grafana-config
            items:
            - key: dashboardConfig.yaml
              path: dashboardConfig.yaml
        - name: dashboard-templates
          configMap:
            defaultMode: 420
            items:
            - key: kubeUPS-dashboard.json
              path: kubeUPS-dashboard.json
            name: kubeups-dashboard