{
 "title": "KubeUPS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Live UPS Load (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "apcupsd_ups_load_percent", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "UPS Load (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "apcupsd_ups_load_percent", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "UPS Line Volts (v)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    { "expr": "apcupsd_line_volts", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Battery Charge (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_charge_percent", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Battery Time Left ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}